### ISSUE TITLE
Note: Auth returns 409 with public profile

### ISSUE THREAD

**Issue by tapsboy** [reklatsmasters/verdaccio-github-token#2]
If the user's org membership is public, only then github makes it visible here:

https://api.github.com/users/{YOUR_GITHIB_USERNAME}/orgs

The plugin returns 409 if it the membership isn't visible to public. Not sure if this is a bug, but it will nice to add this to README

**Comment by reklatsmasters** [comment]
Good point, @tapsboy. I wrote this note in our private registry's repo after first release.
